title: Your Blog Title
description: >- 
  This is your blog where you write about your thoughts and experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
theme: minima

# Build settings
markdown: kramdown

